import type { Metadata } from "next";
import { Oswald, Poppins } from "next/font/google";
import { twMerge } from "tailwind-merge";
import State from "./State";
import "./globals.css";

const oswald = Oswald({
  variable: "--font-heading",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-body",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AEON (clone)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          `${oswald.variable} ${poppins.variable} antialiased`,
          "h-screen font-body text-gray-900 bg-gray-50",
        )}
      >
        <State children={children} />
      </body>
    </html>
  );
}
